baseURL = 'https://about.neodb.social/'
languageCode = 'zh-cn'
title = 'NeoDB 档案馆'
theme = "PaperMod"

[params]
  ShowToc = true
  TocOpen = true
  ShowShareButtons = true
  editPost.URL = 'https://github.com/neodb-social/about.neodb.social/blob/main/content'
  editPost.Text = '✍ 为本文提供修改建议'
  editPost.appendFilePath = true
